# Generated by Django 4.2.1 on 2023-06-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ('user', 'favorite_recipe'),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Содержит название ингридиента (макс 150 символов)', max_length=150, verbose_name='Название ингридиента')),
                ('measurement_unit', models.CharField(help_text='Содержит единицы измерения ингридиента (макс 50 символов)', max_length=50, verbose_name='Единицы измерения ингридиента')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('name', 'measurement_unit'),
            },
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Содержит количество ингридиента', verbose_name='Количество ингридиента')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Содержит название рецепта (макс 150 символов)', max_length=150, verbose_name='Название рецепта')),
                ('image', models.ImageField(help_text='Содержит фото рецепта', upload_to='recipes/media/', verbose_name='Фото рецепта')),
                ('description', models.TextField(help_text='Содержит описание рецепта', verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(help_text='Содержит время приготовления рецепта', verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Содержит название тэга (макс 150 символов)', max_length=150, unique=True, verbose_name='Название тэга')),
                ('color', models.CharField(help_text='Содержит цвет тэга в HEX формате', max_length=7, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(help_text='Содержит короткий текст для доступа к тэгу через url', unique=True, verbose_name='Тексты ссылки тэга')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TagRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_in_cart', models.ForeignKey(help_text='Recipe which added to cart by a certain user', on_delete=django.db.models.deletion.CASCADE, related_name='added_to_cart', to='recipes.recipe', verbose_name='Recipe in cart')),
            ],
            options={
                'verbose_name': 'Shopping cart',
                'verbose_name_plural': 'Shopping carts',
                'ordering': ('user', 'recipe_in_cart'),
            },
        ),
    ]
