# Generated by Django 4.2.1 on 2023-06-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user', 'favorite_recipe'), 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user', 'recipe_in_cart'), 'verbose_name': 'Shopping cart', 'verbose_name_plural': 'Shopping carts'},
        ),
    ]
