# Generated by Django 4.2.1 on 2023-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_alter_ingredientrecipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                help_text='Содержит список ингридиентов',
                through='recipes.IngredientRecipe',
                to='recipes.ingredient',
                verbose_name='Ингридиенты',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                help_text='Содержит список тэгов',
                through='recipes.TagRecipe',
                to='recipes.tag',
                verbose_name='Тэги',
            ),
        ),
    ]
