# Generated by Django 4.2.1 on 2023-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingridient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(help_text='Содержит название ингридиента (макс 150 символов)', max_length=150, verbose_name='Название ингридиента'),
        ),
    ]
