# Generated by Django 4.2.1 on 2023-06-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
    ]
