# Generated by Django 4.2.1 on 2023-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_ingredients_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Содержит фото рецепта', upload_to='media/', verbose_name='Фото рецепта'),
        ),
    ]
