# Generated by Django 4.2.1 on 2023-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0007_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('favorite_recipe', 'user'), name='unique_favorite'
            ),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(
                fields=('recipe_in_cart', 'user'), name='unique_good'
            ),
        ),
    ]
