# Generated by Django 4.2.1 on 2023-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_favorite_unique_favorite_shoppingcart_unique_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Содержит фото рецепта', upload_to='media/', verbose_name='Фото рецепта'),
        ),
    ]
