# Generated by Django 4.2.1 on 2023-07-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date', 'name'), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
