# Generated by Django 4.2.1 on 2023-07-04 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0013_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(
                help_text='Содержит количество ингридиента',
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Количество ингридиента',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(
                help_text='Содержит время приготовления рецепта',
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Время приготовления',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(
                help_text='Содержит цвет тэга в HEX формате',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        regex='^#[0-9a-fA-F]{6}$'
                    )
                ],
                verbose_name='Цвет тэга',
            ),
        ),
    ]
