# Generated by Django 4.2.1 on 2023-06-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('follower',), 'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
    ]
