# Generated by Django 4.2.1 on 2023-06-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
